name: thecloudblog
favicon: null
layout_spectrum: 0.1282508890144527
typography_spectrum: 0.5375708658248186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.37079125875607133
  lightness: 0.4658849462866783
  saturation: 0.9427164066582918
  rhythmicContrast: 0.06770611321553588
purpose: []
